name: "GCS Setup"
description: "Setup Google Cloud Storage authentication"

runs:
  using: "composite"
  steps:
    - name: Get Service Account Key
      id: secrets
      run: |
        JSON_KEY=$(dotenvx get BASE64_ENCODED_SERVICE_ACCOUNT_JSON | base64 -d)
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "credentials_json<<$EOF" >> "$GITHUB_OUTPUT"
        echo "$JSON_KEY" >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        credentials_json: "${{ steps.secrets.outputs.credentials_json }}"

    - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
