# Name of this app
service: fizzy
image: tifandotme/fizzy

#-- About your deployment --#

# Where to deploy fizzy
servers:
  web:
    - box.javanese-pound.ts.net

# How you connect to your server
ssh:
  user: eddies
sshkit:
  max_concurrent_starts: 1
  dns_retries: 5
  pool_idle_timeout: 300

# Automatic SSL
proxy:
  ssl: true
  host: fizzy.tifan.me

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  clear:
    BASE_URL: https://fizzy.tifan.me # The public URL of your Fizzy instance
    MAILER_FROM_ADDRESS: fizzy@mail.tifan.me # The email "from" address that Fizzy sends email from
    SMTP_ADDRESS: smtp.mailgun.org # The SMTP server you'll use to send email
    MULTI_TENANT: false # Set to true to allow multiple accounts to sign up
    SOLID_QUEUE_IN_PUMA: false # Run background jobs in the app container
    WEB_CONCURRENCY: 1 # Use single-worker mode to reduce memory overhead
    JOB_CONCURRENCY: 1 # Limit background job worker to 1 thread to reduce memory usage

#-- General configuration --#

# Use GitHub Container Registry
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Handy aliases for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f # follow
  backup: server exec "$HOME/backup-fizzy.sh"
  backup-logs: server exec "cat $HOME/.logs/fizzy-backup.log"
  lzd: server exec --interactive "TERM=xterm-256color $HOME/.local/bin/lazydocker"
  btm: server exec --interactive "TERM=xterm-256color /usr/bin/btm -g --process_memory_as_value"
  # console: app exec --interactive --reuse "bin/rails console"
  # dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - /home/eddies/fizzy-storage:/rails/storage

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
